version: '3'

services:
  rtsp_simple_server:
    image: aler9/rtsp-simple-server
    container_name: rtsp_server
    ports:
      - "8554:8554"
    networks:
      - broadcaster_network


  broadcaster_service:
    image: theclayman/broadcaster_service
    container_name: broadcaster_service
    ports:
      - "5000:5000"
    volumes:
      - videos:/home/myuser/code/videos
      - ./Broadcaster_service/config.json:/home/myuser/code/config.json
    networks:
      - broadcaster_network

  broadcaster_front:
    image: theclayman/broadcaster_front
    container_name: broadcaster_front
    ports:
      - "3000:3000"
    volumes:
      - ./Broadcaster_front/src/properties.json:/app/src/properties.json
    networks:
      - broadcaster_network

volumes:
  videos:

networks:
  broadcaster_network:
    driver: bridge

