name: Docker Image CI

on:
  push:
    branches: [ "github_actions" ]
  pull_request:
    branches: [ "github_actions" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd ./Broadcaster_service docker build . --file Dockerfile --tag theclayman/broadcaster_service:$(date +%s)
