name: Docker Image CI

on:
  push:
    branches: [ "github_actions" ]
  pull_request:
    branches: [ "github_actions" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Retrieve version
      run: |
        echo "TAG_NAME=$(cat Broadcaster_front/src/properties.json | grep version | grep -o '[0-9]\.[0-9]\.[0-9]')" >> $GITHUB_OUTPUT
      id: version
    - name: Set version to prop file
      run : |
        sed -i 's\${{ steps.version.outputs.TAG_NAME }}\${{ steps.version.outputs.TAG_NAME }}.${{github.run_number}}\g' Broadcaster_front/src/properties.json
        echo "version number:"
        cat Broadcaster_front/src/properties.json
        
    - name: Build the Docker image
      run: cd ./Broadcaster_service && docker build . --file Dockerfile --tag theclayman/broadcaster_service:v${{ steps.version.outputs.TAG_NAME }}.${{github.run_number}}
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
    - name: Log into registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   # - name: Push to Dockerhub
   #   run: docker push theclayman/broadcaster_service:v${{ steps.version.outputs.TAG_NAME }}.${{github.run_number}}
