name: Docker Image CI

on:
  push:
    branches: [ "github_actions" ]
  pull_request:
    branches: [ "github_actions" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Retrieve version
      run: |
        echo "TAG_NAME=$(cat Broadcaster_front/src/properties.json | grep version | grep -o '[0-9]\.[0-9]\.[0-9]')" >> $GITHUB_OUTPUT
      id: version
    - name: Build the Docker image
      run: cd ./Broadcaster_service && docker build . --file Dockerfile --tag theclayman/broadcaster_service:v${{ steps.version.outputs.TAG_NAME }}.${{github.run_number}}
